name: Build & Test
on: [pull_request, create]

jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Build & Test
    runs-on: macos-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: brew tap slp/krunkit && brew install virglrenderer clang-format

      - name: Clone libkrun source
        run: git clone https://www.github.com/containers/libkrun.git ~/libkrun

      - name: Build libkrun source
        run: cd ~/libkrun && make EFI=1 NET=1 BLK=1 GPU=1 && sudo make EFI=1 NET=1 BLK=1 GPU=1 install && cd ~/

      - name: Build
        run: make LIBKRUN_EFI=/usr/local/lib/libkrun-efi.dylib

      - name: Test
        run: cargo test --release --verbose -- --show-output
